#!/usr/bin/perl
use strict;
use warnings;
use NetSNMP::agent (':all');
use NetSNMP::ASN;
use NetSNMP::OID;


sub vaba
 {
	my ($handler, $registration_info, $request_info, $requests) = @_;
	my $request;
	for($request = $requests; $request; $request = $request->next()) 
	{
		my $givenoid = $request->getOID();
		my @oidarray = split/[.]/,$givenoid;
		my $lastoid = $oidarray[-1];
		if ($request_info->getMode() == MODE_GET)
		{
			if ($givenoid == new NetSNMP::OID("1.3.6.1.4.1.4171.40.1")) 
			{
				$request->setValue(ASN_COUNTER, time);
			} 
			elsif ($givenoid > new NetSNMP::OID("1.3.6.1.4.1.4171.40.1")) 
			 {
				
				my $number = $lastoid -1;
				my %file;
				my $unixtime = time(); 

				open FH, "/counters.conf" or die "Can't open FILE $!";

				while (<FH>)
				{

				  chomp;                                                    
				  my ($id,$bitrate) = split(/,\s?/);                         
				  $file{$id} = $bitrate;
				}
				if (exists($file{$number}))
				{
					my $counter_time = $file{$number} * $unixtime;
					$request->setValue(ASN_COUNTER, $counter_time);
				}
				
				
				
			   }
		}
	}
}

my $agent = new NetSNMP::agent();
$agent->register("subagent", '1.3.6.1.4.1.4171.40', \&vaba);
