#!/usr/bin/python


import sys
import os 
import subprocess 

a=sys.argv
x = []
for i in range(3,len(sys.argv)):
  x.append(sys.argv[i])



def read_output(command):
    process = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    return iter(process.stdout.readline, "")

for output in read_output(['/home/vamshi/Desktop/prober', a[1], a[2], '-1'] + x):
    for i in range(3,len(sys.argv)):
        oid=sys.argv[i]
        s= output.split('|') 
        timevalue = s[0].split(" ")
        rt1=s[1].split(" ")
        frt=s[-2].split(" ")
        v=s[2:-1]
        v.insert(0,rt1[1])
        v.append(frt[0])
        #print oid,v[i-3],timevalue[0]
    
        os.system("curl -i -XPOST 'http://localhost:8086/write?db=A3&u=ats&p=atslabb00&precision=s' --data-binary 'rate,oid=%s values=%s %s'"%(oid,v[i-3],timevalue[0]))
        
