#!/usr/bin/python


import sys
import os 
import subprocess 

a=sys.argv
x = []
for i in range(3,len(sys.argv)):
  x.append(sys.argv[i])

k=[]

def read_output(command):
    process = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    return iter(process.stdout.readline, "")

for output in read_output(['unbuffer','/tmp/A2/prober', a[1], a[2], '-1'] + x):
    for i in range(3,len(sys.argv)):
        oid=sys.argv[i]
        s= output.split('|') 
        s = [x.strip(' ') for x in s] 
        stripped_line = [sa.rstrip() for sa in s]  
        timevalue=stripped_line[0]
        myrate = stripped_line[1:]
        #print type(int(timevalue)), type(oid), type(float(myrate[i-3]))
        os.system("curl -i -XPOST 'http://localhost:8086/write?db=A3&u=ats&p=atslabb00&precision=s' --data-binary 'rate,oid='%s' value=%f %d'" %(oid,float(myrate[i-3]),int(timevalue)))
